name: "karsajobs-ui" # Nama WorkFlow

on:
 push:
  branches: ["karsajobs-ui"] # Pemicu: Hanya branch "karsajobs-ui"

jobs:
 lint-dockerfile: # Melakukan linting pada Dockerfile
  runs-on: ubuntu-latest # Dijalankan pada Ubuntu terbaru
   steps:
    - uses: actions/checkout@v4.2.2 # CheckOut kode dari repository
    - uses: hadolint/hadolint-action@v3.1.0 # Menjalankan Hadolint untuk memeriksa kesalahan pada Dockerfile
      with:
       dockerfile: ./Dockerfile # Lokasi Dockerfile

 build-app-karsajobs-ui:
  needs: lint-dockerfile # Menunggu job lint-dockerfile selesai
  runs-on: ubuntu-latest # Dijalankan pada Ubuntu terbaru
  steps:
   - uses: actions/checkout@v4.2.2 # CheckOut kode dari repository

   - name: Docker build # Membangun image Docker
     run: docker buildx build --platform linux/amd64 --provenance=false --sbom=false -t ghcr.io/vourone/karsajobs-ui:latest . # Membuat image Docker

   - name: Docker login # Melakukan login ke GitHub Container Registry
     run: docker login --username Vourone --password ${{ secrets.GH_PAT }} ghcr.io # Menggunakan token untuk autentikasi

   - name: Docker push # Mengunggah image Docker
     run: docker push ghcr.io/vourone/karsajobs-ui:latest # Mendorong image Docker terbaru ke GitHub Container Registry
